import "./globals.css"
import { cn } from "@/lib/utils"
import { Inter } from "next/font/google"
import { Providers } from "./providers"
import type { Metadata } from "next"
import Navbar from "@/components/Navbar"
import { Toaster } from "@/components/ui/sonner"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        suppressHydrationWarning
        className={cn("min-h-screen flex flex-col", inter.className)}
      >
        <Providers>
          <Navbar />
          <main>{children}</main>
        </Providers>
        <Toaster theme="system" position="top-center" richColors />
      </body>
    </html>
  )
}
